apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./app-of-apps/manifests
   
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: 
      prune: true 
      selfHeal: true 
